version: '3.8'

services:
  web:
    build:
      dockerfile: docker/Dockerfile.web
      context: .
    image: "mac/django-app:1.0"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/app/
    ports:
      - 8200:8000 #host port:container port
      - 8300:8001 #for dev server
    env_file:
      - env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    env_file:
      - env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
