FROM python:3.9.6-alpine

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev bash fish

RUN pip install --upgrade pip
COPY ./src/requirements.txt .
RUN pip install -r requirements.txt

WORKDIR /app

CMD while true; do sleep 10; done