# Generated by Django 3.2.6 on 2022-09-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(max_length=250),
        ),
    ]
