# Generated by Django 3.2.6 on 2022-09-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20220927_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(choices=[('dou', 'dou'), ('other', 'other')], default='other', max_length=250),
        ),
    ]
